### ISSUE TITLE
Example view usage?

### ISSUE THREAD

**Issue by pointclickreality** [joecampo/laravel-shipstation#10]
Hi,

I am trying to use this package to pull from Shipstation into Laravel. All goes well as I am able to get the results from Controller using dd($orders). But when i go to use it in view (eg: foreach $orders as $order), when I attempt to access the properties like so $order->orderNumber or $order->orders["orderNumber"] . Can you please help me to understand why I am getting the following error "htmlspecialchars() expects parameter 1 to be string, array given" or just show me what I need to do to be able to display the get requests from Shipstation in a view. It works fine for $users but the $orders is giving me a problem.

Thanks, a Million

**Comment by joecampo** [comment]
Hi there - 

It sounds like you have a nested object/array in the results. See your error:  expects parameter 1 to be string, array given. Dump & die the results and see if it is under another key. 

IIRC they're nested under ->orders. So it's probably something like foreach($orders->orders as $order).
