### ISSUE TITLE
Custom Store

### ISSUE THREAD

**Issue by smccoy78** [joecampo/laravel-shipstation#12]
How to create custom store endpoints? Is this something that your plugin is able to do. If not, is this a feature you would be interested in adding?

**Comment by squatto** [comment]
Most of the ShipStation API endpoints support a `storeId` input parameter. Does that do what you need it to or is there something further that you need?

_(sorry to resurrect a 2 year old issue - I'm dealing with ShipStation a lot right now and figured I'd ask!)_
