### ISSUE TITLE
Create label for order

### ISSUE THREAD

**Issue by DEVOTESTER** [joecampo/laravel-shipstation#15]
How can i create label for an order. 
Everytime i hit the command it gives me 500 Error 

I am passing these arguments
$label = new LaravelShipStation\Models\Order();
        $label->orderId = $orderid;
        $label->carrierCode = 'stamps_com';
        $label->serviceCode = 'stamps_com';
        $label->packageCode = 'package';
        $label->confirmation = null;
        $label->testLabel = false;
        $label->shipDate = '2019-09-28';

        $label_data = $shipStation->orders->post($label, 'createlabelfororder');

Error getting:
Server error: `POST https://ssapi.shipstation.com/orders/createlabelfororder` resulted in a `500 Internal Server Error` response: {"Message":"An error has occurred.","ExceptionMessage":"Object reference not set to an instance of an object.","Exceptio (truncated...)

**Comment by joecampo** [comment]
Hi there, the error you've posted is truncated, but is one that is coming from the ShipStation API. I'd imagine you'd need to create the order in ShipStation prior to being able to create a label for an order.
