### ISSUE TITLE
What should be the right format for weight and dimensions attributes?

### ISSUE THREAD

**Issue by ameerbjs** [joecampo/laravel-shipstation#16]
Hello, 

I am trying to create a shipment with weight and dimensions of the product. But its showing me an error pasted below: 

> message: "Client error: `POST https://ssapi.shipstation.com/orders/createorder` resulted in a `400 Bad Request` response:↵{"Message":"The request is invalid.","ModelState":{"apiOrder.items[0].weight":["Cannot deserialize the current JSON arra (truncated...)↵

In the package the datatype for the weight is array, so I am trying to send this kind of format there.

```$order->weight               = [1,2];```
```$order->dimensions        =[1,2,3];```

Please suggest me the exact format to send with and also I need assistance with 
> $requestedShippingService

How could I get the existing shipping service from my account to map?

Thanks!

**Comment by joecampo** [comment]
Please refer to the ShipStation docs. You have to use a Weight model. https://shipstation.docs.apiary.io/#reference/orders/createupdate-order

https://www.shipstation.com/developer-api/#/reference/model-weight

There is a provided DTO that you can use: https://github.com/joecampo/laravel-shipstation/blob/master/src/Models/Weight.php

**Comment by ameerbjs** [comment]
Thanks!
