### ISSUE TITLE
Using Webhooks

### ISSUE THREAD

**Issue by abishekrsrikaanth** [joecampo/laravel-shipstation#18]
@joecampo As mentioned here, https://help.shipstation.com/hc/en-us/articles/360025856252-ShipStation-Webhooks#UUID-1a4971f4-8fb5-f4a5-c399-f36cff610435_UUID-851a5fd2-a181-b302-41de-c32ced43eb92, the payload received from the webhooks are resource url's that needs to be separately requested using the same authentication header that the rest of the API calls use.

Is there a method to call the resource url received on the webhook?

**Comment by joecampo** [comment]
@abishekrsrikaanth Hi there - I've never used them (weren't supported when we wrote this pkg), but someone PR'd the webhooks endpoint. You should be able to get on that endpoint: `$shipStation->webhooks->get` to fetch the resource_url the Webhook passes.

**Comment by abishekrsrikaanth** [comment]
I would appreciate if someone using webhooks could give an example of it usage.
