### ISSUE TITLE
Rate Limiting / Too Many Requests

### ISSUE THREAD

**Issue by dmotors** [joecampo/laravel-shipstation#2]
Hello,

I noticed even though you have a pause to detect if making a lot of requests by average, I still get occasional "too many requests" from ShipStation. When this happens it is usually the addtags orders call and it can loop through literally 1000+ orders that need to either add a tag and/or removetag call both per order.

Would you suggest I increase the 1.5 sleep or do you suggest something else?

**Comment by joecampo** [comment]
Interesting - I'll take a peek. Are you using 3.0.0? 

Their API can be a bit unpredictable at times (random 401's, 500's from my experience). Can you try increasing it and let me know if that resolves the issue?

**Comment by dmotors** [comment]
Yes I am using 3.0.0.

I totally agree with you on the API being so unpredictable! I'm glad I'm not alone there!

Also, for even more proactive prevention, I have added a try/catch and will retry the call 3 times with a 15 sec sleep in between each retry to further promote a more successful non-script breaking situation.

I will try increasing to see if it helps.

Thanks.

**Comment by joecampo** [comment]
I was thinking about implementing Guzzle's retry middleware into this package to catch/retry some of those random (and incorrect) API responses.

**Comment by dmotors** [comment]
It's hard to determine if increasing the seconds on the sleep made any big impact or not as it's still showing to be quite random API responses. It might have helped to some degree but perhaps the core issue is ShipStations 401/500's.

**Comment by joecampo** [comment]
I reached out to them back in June to report the random responses I was getting from the API & gave them some examples, but never got a solid response (and it never got any better).

I'm going to go ahead and leave your issue open for now until I can implement something like a retry middleware.

**Comment by dmotors** [comment]
Yes I did remember asking their support as well but nothing came out of it.

Sounds good you are possibly implementing the retry middleware. At that point I will remove my try/catch in my logic.

Do you think the 1.5 sleep could be a config option instead of trying to modify vendor/fork/override with custom class?

Either way thanks.

**Comment by joecampo** [comment]
I'd definitely keep the try/catch logic in there just in case the API really goes crazy (which it has on me a few times).

I think having the sleep configurable is a good idea. I'll add that. Thanks for help!

**Comment by shane-scalable** [comment]
I am having to integrate with ShipStation's API as well, and did have reserves when I saw the way in which the rate limiting is being done. 

I am not a fan of sleeping after the response as this is slowing down a lot of processes and holding memory in the process.  I was working on my own integration when I found this package, and will try to create a pull-request with some suggested updates to the rate-limiting to use a Redis cache as I had done on my implementation. 

UPDATE:
As a quick add for now until I can clean it up and create a pull request I did the following: (in case it helps anyone)
added a config to shipstation.php: `'redisRateLimiter' => true`
Updated the LaravelShipStation/ShipStation entity to include 2 new properties and 3 new methods.  I call one of the methods BEFORE the API request to honor the cached rate limit info if it is set.  I also call AFTER the API request to set the data in the cache (if configuration is set)
ShipStation.php:
```
<?php
namespace LaravelShipStation;

use GuzzleHttp\Client;
use GuzzleHttp\Psr7\Response;
use Illuminate\Support\Facades\Redis;

class ShipStation extends Client
{

    /**
     * @var string The current endpoint for the API. The default endpoint is /orders/
     */
    public $endpoint = '/orders/';

    /**
     * @var array Our list of valid ShipStation endpoints.
     */
    private $endpoints = [
        '/accounts/',
        '/carriers/',
        '/customers/',
        '/fulfillments/',
        '/orders/',
        '/products/',
        '/shipments/',
        '/stores/',
        '/users/',
        '/warehouses/',
        '/webhooks/'
    ];

    /**
     * @var string Base API URL for ShipStation
     */
    private $base_uri = 'https://ssapi.shipstation.com';

    /**
     * @var string The Redis cache key for handling rate limits
     */
    private $rateBucketCacheKey = 'shipstation.rate_bucket';

    /**
     * @var bool Determines whether to use Redis cache for rate limiting
     */
    private $redisRateLimiter;

    /**
     * ShipStation constructor.
     *
     * @param  string  $apiKey
     * @param  string  $apiSecret
     * @throws \Exception
     */
    public function __construct($apiKey, $apiSecret)
    {
        if (!isset($apiKey, $apiSecret)) {
            throw new \Exception('Your API key and/or private key are not set. Did you run artisan vendor:publish?');
        }

        parent::__construct([
            'base_uri' => $this->base_uri,
            'headers'  => [
                'Authorization' => 'Basic ' . base64_encode("{$apiKey}:{$apiSecret}"),
            ]
        ]);

        $this->redisRateLimiter = (config('shipstation.redisRateLimiter') ?: false);
    }

    /**
     * Get a resource using the assigned endpoint ($this->endpoint).
     *
     * @param  array  $options
     * @param  string  $endpoint
     * @return \stdClass
     */
    public function get($options = [], $endpoint = '')
    {
        $this->checkRateLimits();

        $response = $this->request('GET', "{$this->endpoint}{$endpoint}", ['query' => $options]);

        $this->handleResponseMeta($response);

        return json_decode($response->getBody()->getContents());
    }

    /**
     * Post to a resource using the assigned endpoint ($this->endpoint).
     *
     * @param  array  $options
     * @param  string  $endpoint
     * @return \stdClass
     */
    public function post($options = [], $endpoint = '')
    {
        $this->checkRateLimits();

        $response = $this->request('POST', "{$this->endpoint}{$endpoint}", ['json' => $options]);

        $this->handleResponseMeta($response);

        return json_decode($response->getBody()->getContents());
    }

    /**
     * Delete a resource using the assigned endpoint ($this->endpoint).
     *
     * @param  string  $endpoint
     * @return \stdClass
     */
    public function delete($endpoint = '')
    {
        $this->checkRateLimits();

        $response = $this->request('DELETE', "{$this->endpoint}{$endpoint}");

        $this->handleResponseMeta($response);

        return json_decode($response->getBody()->getContents());
    }

    /**
     * Update a resource using the assigned endpoint ($this->endpoint).
     *
     * @param  array  $options
     * @param  string  $endpoint
     * @return \stdClass
     */
    public function update($options = [], $endpoint = '')
    {
        $this->checkRateLimits();

        $response = $this->request('PUT', "{$this->endpoint}{$endpoint}", ['json' => $options]);

        $this->handleResponseMeta($response);

        return json_decode($response->getBody()->getContents());
    }



    /**
     * Check to see if we are about to rate limit and pause if necessary.
     *
     * @param Response $response
     */
    public function sleepIfRateLimited(Response $response)
    {
        $rateLimit = $response->getHeader('X-Rate-Limit-Remaining')[0];
        $rateLimitWait = $response->getHeader('X-Rate-Limit-Reset')[0];

        if (($rateLimitWait / $rateLimit) > 1.5) {
            sleep(1.5);
        }
    }

    /**
     * Appropriately handle the rate limiting data in the response
     * @param Response $response
     */
    protected function handleResponseMeta(Response $response)
    {
        if($this->redisRateLimiter) {
            $this->cacheRateLimitInfo($response);
        } else {
            $this->sleepIfRateLimited($response);
        }
    }

    /**
     * Use Redis cache to accommodate rate limits
     */
    protected function checkRateLimits()
    {
        if ($this->redisRateLimiter) {
            $cache = Redis::connection();

            // If there is a cached rate bucket AND the bucket is empty then sleep until the next window
            if ($cache->exists($this->rateBucketCacheKey)
                && ($rateBucket = json_decode($cache->get($this->rateBucketCacheKey), true))
                && $rateBucket['bucket'] < 1
            ) {
                // The next window will be the current timestamp minus the timestamp of the next window opening.
                sleep((new \DateTime())->getTimestamp() - $rateBucket['ttl']);
            }
        }
    }

    /**
     * @param Response $response
     */
    protected function cacheRateLimitInfo(Response $response)
    {
        $cache = Redis::connection();

        $cache->setex($this->rateBucketCacheKey,
            $response->getHeader('X-Rate-Limit-Reset')[0], // Sets the ttl to remove itself as soon as the next window hits
            json_encode([
                'bucket' => $response->getHeader('X-Rate-Limit-Remaining')[0],
                'ttl' => (new \DateTime('+' . $response->getHeader('X-Rate-Limit-Reset')[0] . ' secs'))->getTimestamp()
            ])
        );
    }

    /**
     * Set our endpoint by accessing it via a property.
     *
     * @param  string $property
     * @return $this
     */
    public function __get($property)
    {
        if (in_array('/' . $property . '/', $this->endpoints)) {
            $this->endpoint = '/' . $property . '/';
        }

        $className = "LaravelShipStation\\Helpers\\" . ucfirst($property);

        if (class_exists($className)) {
            return new $className($this);
        }

        return $this;
    }
}
```

**Comment by joecampo** [comment]
@shane-scalable Awesome! Thank you! I totally agree with you regarding sleeping - at the time I needed a quick solution.

**Comment by jsdecena** [comment]
In unit testing, we only test what we own right? In this case, the reason you are getting "too many requests" is because of the security in place on the API side. I think the way to test an external API is to mock their response and do actions within your app depending on the type of the response? Btw, this is a good package, to begin with :) Thanks bro!

**Comment by squatto** [comment]
FYI I just added some methods in #19 that expose the rate limiting information from ShipStation. It doesn't *fix* the rate limiting, but it gives you the information that you need to implement your own rate limiting logic.
