### ISSUE TITLE
Is there a way to set the API key and secret dynamically?

### ISSUE THREAD

**Issue by eswachsman** [joecampo/laravel-shipstation#22]
Is there a way to set the API key and secret dynamically so I can make requests to different ShipStation accounts? (I am building a SaaS)

**Comment by joecampo** [comment]
Hey 👋

You can change the configuration data on the fly using the `config` helper.

For example:

```php
config(['shipstation.apiKey' => '123456']);
```

**Comment by eswachsman** [comment]
Thanks!
