### ISSUE TITLE
How to manage multiple orders update?

### ISSUE THREAD

**Issue by MyWorkHistory** [joecampo/laravel-shipstation#23]
Hello , Everybody.
Thanks for your work.
Well Can I ask some questions ?
Now I am using this code for shipstation API.
I am updating the multiple orders at a time for example +5000 orders - update  the tagIds.
So I am using $shipstation->orders->post($option,'createorders');
it works only when I try to add new tagIds.
But When I try remove some tagIds it is not working..
Is there any some advice  for this issue ?
Hope to hear from you soon.
Thanks 
Chao

**Comment by joecampo** [comment]
Hi there,

Tags are not something I personally use so I don't really have any recommendation other than looking through the ShipStation API docs.

Perhaps this is something you can automate based on products as they allow you to tag products and orders of those products will inherit the tags: https://help.shipstation.com/hc/en-us/articles/360026156931-Order-Tags#add-tags-automatically-0-5

**Comment by MyWorkHistory** [comment]
Thanks so much.
Chao
