### ISSUE TITLE
Why i get error for $this->app['LaravelShipStation\ShipStation'];

### ISSUE THREAD

**Issue by Kernel1453** [joecampo/laravel-shipstation#27]
Hi all,

i'm new for both laravel and shipstation. I'm trying to send / create new order. but when i try to send new order returns error for  $shipStation = $this->app['LaravelShipStation\ShipStation'];

Undefined property: App\Http\Controllers\SettingsController::$app

what should i do for overcome this issue? any information will be appreciated.

Best Regards

**Comment by joecampo** [comment]
Yeah docs should be updated, you can use:

```app('LaravelShipStation\ShipStation')``` or ```resolve('LaravelShipStation\ShipStation')```

**Comment by Kernel1453** [comment]
@joecampo thank you very very much, it worked.
