### ISSUE TITLE
PrintLabel, get carriers lbs price

### ISSUE THREAD

**Issue by Kernel1453** [joecampo/laravel-shipstation#28]
Hello,
Thank for this package. It helps too much for our project. We have questions.
How can we create labels for our orders that created manually?
How can we check prices for our account, which carrier, which lbs return price?
Thank you,
Best regards

**Comment by joecampo** [comment]
Hi there,

I'm not sure. These aren't use cases I've personally ever had to implement. I'd recommend reading through their API docs to determine what is/isn't possible.
