### ISSUE TITLE
Missing /fulfillments endpoint

### ISSUE THREAD

**Issue by andobolocco** [joecampo/laravel-shipstation#3]
according to shipstation docs now we can list /fulfillments as a separate request, this wrapper does not include that endpoint and there's no way to extend it in laravel because $endpoints is a private property and there is no setter method to add any.

anyone encountered this issue? can we simply add '/fulfillments' to the $endpoints array?

thanks in advance

**Comment by andobolocco** [comment]
@joecampo any plans on adding this?

**Comment by joecampo** [comment]
Hi there - I added the endpoint.

**Comment by andobolocco** [comment]
great! thank you!
