### ISSUE TITLE
webhooks

### ISSUE THREAD

**Issue by redragonx** [joecampo/laravel-shipstation#9]
I'm confused on how these are implemented in Shipstation. The docs don't say much about them other than in the custom store guide. I have some questions.

1. Do they allow JSON like their apis or what? I'd prefer to go with JSON.
2. If they do, how can I receive JSON, not XML?

**Comment by joecampo** [comment]
I'm not sure I follow your question and I don't think it has anything to do with this library. IIRC, webhooks can be setup in your account preferences. The API will allow you to list existing webhooks and subscribe/unsubscribe to them.
